### ISSUE TITLE
大量攻击可能导致服务奔溃？

### ISSUE THREAD

**Issue by starnightcyber** [hacklcx/HFish#120]
早上查看蜜罐，发现已经不能访问了，然后重启服务切到大屏，如下。
![image](https://user-images.githubusercontent.com/19260696/101718275-d6bea800-3adb-11eb-844c-5348685522dd.png)
感觉可能爆炸了，重启服务没多久，然后又挂了，以下是出错信息。
```
panic: concurrent write to websocket connection

goroutine 1347 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc000948810, 0x1, 0x0, 0x0, 0x0, 0x15f9460, 0x0)
	/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:610 +0x60e
github.com/gorilla/websocket.(*messageWriter).Close(0xc000948810, 0x0, 0xc000958c50)
	/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:724 +0x65
github.com/gorilla/websocket.(*Conn).beginMessage(0xc000316840, 0xc000240870, 0x1, 0xc000958e60, 0xab16a5)
	/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:473 +0x262
github.com/gorilla/websocket.(*Conn).NextWriter(0xc000316840, 0x1, 0xc000958d90, 0x203000, 0x203000, 0x203000)
	/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:513 +0x53
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc000316840, 0xcd1860, 0xc000240840, 0x15f9460, 0x0)
	/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/json.go:24 +0x49
HFish/view/data.Send(0xc000240840)
	/source/view/data/view.go:239 +0xc5
HFish/core/alert.AlertDataWs(0xdcb715, 0x3, 0xdcbaea, 0x4, 0xc000db8020, 0x10, 0xc000db8010, 0x8, 0xc000db8030, 0xb, ...)
	/source/core/alert/alert.go:181 +0x654
HFish/core/report.alertx(0xc000dfc7b8, 0x6, 0xdcb715, 0x3, 0xdcbaea, 0x4, 0xc000db8020, 0x10, 0xc000db8010, 0x8, ...)
	/source/core/report/report.go:45 +0x445
created by HFish/core/report.ReportHttp
	/source/core/report/report.go:387 +0x3e6

[1]+  Exit 2                  ./HFish run
```
可能是并发写入导致服务奔溃。

**Comment by starnightcyber** [comment]
现在美国变成了这个球样 ~ 
![image](https://user-images.githubusercontent.com/19260696/101729645-7fc4cd00-3af3-11eb-8bb7-6ee85f4a224e.png)

**Comment by GuyPsychoBlogs** [comment]
俺也一样，阿里云服务器天天有美国http代理

**Comment by starnightcyber** [comment]
> 俺也一样，阿里云服务器天天有美国http代理

外部蜜罐这个可能是hold不住了 ~
