### ISSUE TITLE
从0.6.4升级到0.6.5 发现一个问题

### ISSUE THREAD

**Issue by ym2011** [hacklcx/HFish#128]
[GIN-debug] POST   /api/v1/post/plug_report  --> HFish/view/api.ReportPlugWeb (3 handlers)
heart url: https://hfish.io/info?version=0.6.5&status=2&os=linux-amd64
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa4b222]

goroutine 11 [running]:
github.com/gohouse/gorose.(*Engin).GetExecuteDB(0x0, 0xc0000c4cf0)
        /go/pkg/mod/github.com/gohouse/gorose@v0.0.0-20190830103550-ad3ce0985b9e/engin.go:107 +0x22
github.com/gohouse/gorose.NewSession(0xee0d00, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/gohouse/gorose@v0.0.0-20190830103550-ad3ce0985b9e/session.go:35 +0x63
github.com/gohouse/gorose.NewOrm(0xee0d00, 0x0, 0x16006e0)
        /go/pkg/mod/github.com/gohouse/gorose@v0.0.0-20190830103550-ad3ce0985b9e/orm.go:20 +0x53
github.com/gohouse/gorose.(*Engin).NewOrm(...)
        /go/pkg/mod/github.com/gohouse/gorose@v0.0.0-20190830103550-ad3ce0985b9e/engin.go:214
HFish/core/dbUtil.DB(...)
        /source/core/dbUtil/dbUtil.go:37
HFish/utils/setting.clear()
        /source/utils/setting/setting.go:478 +0x195
created by HFish/utils/setting.Run
        /source/utils/setting/setting.go:183 +0x65
该服务器没有外网权限。之前是安装了0.6.4，后来停止后，直接删除，然后重启电脑，再安装0.6.5

**Comment by ym2011** [comment]
这个是以客户端模式运行出错。以服务端运行是正常的。

**Comment by ym2011** [comment]
设置成客户端模式，删除db文件夹、admin文件夹、images文件夹、logs文件夹、static文件夹，程序启动失败成功。
设置成客户端模式，删除db文件夹；保留admin文件夹、images文件夹、logs文件夹、static文件夹，程序启动失败成功。
设置成客户端模式，保留db文件夹，删除admin文件夹、images文件夹、logs文件夹、static文件夹，程序启动成功。
也就是说设置成客户端模式，0.6.5必须保留db文件夹
