### ISSUE TITLE
panic: interface conversion: interface {} is nil, not int64

### ISSUE THREAD

**Issue by fengzhao** [hacklcx/HFish#146]
clone 项目，go build ，然后  ./HFish run 直接报错：

```shell
# ./HFish run
[HFish] 127.0.0.1 - [2021-05-26 07:49:27] 删除过期的威胁情报数据失败  [no such table: hfish_intelligence]
[HFish] 127.0.0.1 - [2021-05-26 07:49:27] 删除过期的威胁情报数据成功  [0]
heart url: https://hfish.io/info?version=0.6.5&status=0&os=linux-amd64
panic: interface conversion: interface {} is nil, not int64

goroutine 1 [running]:
HFish/utils/setting.initCahe()
        /data/HFish/utils/setting/setting.go:162 +0x10b9
HFish/utils/setting.Run()
        /data/HFish/utils/setting/setting.go:401 +0xf85
main.main()
        /data/HFish/main.go:21 +0x12d
```

**Comment by Dawnnnnnn** [comment]
我在M1 Mac下编译的darwin arm64版本也会出现该问题，但是交叉编译出的linux amd64能正常运行，无伤大雅。。

**Comment by Dawnnnnnn** [comment]
调试了一下，大概是因为数据库没初始化，里面数据都是nil，我手动建了个数据库就好了

**Comment by Dawnnnnnn** [comment]
从release里下载0.6.5的打包版本，把hfish.db复制出来应该就可以了
