### ISSUE TITLE
打开大屏展示会出现卡顿，或者直接无法显示

### ISSUE THREAD

**Issue by qq761861** [hacklcx/HFish#227]
打开大屏展示会出现卡顿，或者直接无法显示，server日志报错

2024-01-30 11:05:07.486 [INFO] file_infos.go:48: FetchFileAttackService time: 1970-01-01 08:00:00, serverId: 758648676645081088
2024-01-30 11:05:07.530 [ERRO] file_infos.go:65: updateFileAttack: GetFileAttacks err: GetFileAttacks DoHttpsPostJson err: status code: 502
Stack:
1.  hfish/internal/server/service/daemon.updateFileAttack
    /usr/local/share/internal/server/service/daemon/file_infos.go:65
2.  hfish/internal/server/service/daemon.FetchFileAttackService
    /usr/local/share/internal/server/service/daemon/file_infos.go:49

**Comment by zcbxxx1** [comment]
+1

**Comment by pokebox** [comment]
HFish V3.3.4

打开大屏出错，浏览器控制台日志：
```
TypeError: Permissions check failed
    at full (BigScreen.7a256132.js:1:191311)
    at BigScreen.7a256132.js:1:194420
    at ga (dllSelf.09a1636445d39f4f9ec3.js:22:77937)
    at Pc (dllSelf.09a1636445d39f4f9ec3.js:22:102968)
    at e.unstable_runWithPriority (dllSelf.09a1636445d39f4f9ec3.js:30:3460)
    at Yi (dllSelf.09a1636445d39f4f9ec3.js:22:45496)
    at Cc (dllSelf.09a1636445d39f4f9ec3.js:22:102724)
    at dllSelf.09a1636445d39f4f9ec3.js:22:102636
    at U (dllSelf.09a1636445d39f4f9ec3.js:30:2842)
    at O.port1.onmessage (dllSelf.09a1636445d39f4f9ec3.js:30:1588)
dllSelf.09a1636445d39f4f9ec3.js:22  TypeError: Cannot read properties of null (reading 'length')
    at LastCs (BigScreen.7a256132.js:1:150819)
    at so (dllSelf.09a1636445d39f4f9ec3.js:22:59454)
    at Go (dllSelf.09a1636445d39f4f9ec3.js:22:67693)
    at Ta (dllSelf.09a1636445d39f4f9ec3.js:22:105942)
    at Tc (dllSelf.09a1636445d39f4f9ec3.js:22:90428)
    at Ec (dllSelf.09a1636445d39f4f9ec3.js:22:90353)
    at yc (dllSelf.09a1636445d39f4f9ec3.js:22:87680)
    at dllSelf.09a1636445d39f4f9ec3.js:22:45786
    at e.unstable_runWithPriority (dllSelf.09a1636445d39f4f9ec3.js:30:3460)
    at Yi (dllSelf.09a1636445d39f4f9ec3.js:22:45496)
ha @ dllSelf.09a1636445d39f4f9ec3.js:22
Sa.u.componentDidCatch.n.callback @ dllSelf.09a1636445d39f4f9ec3.js:22
wu @ dllSelf.09a1636445d39f4f9ec3.js:22
mu @ dllSelf.09a1636445d39f4f9ec3.js:22
(匿名) @ dllSelf.09a1636445d39f4f9ec3.js:22
e.unstable_runWithPriority @ dllSelf.09a1636445d39f4f9ec3.js:30
Yi @ dllSelf.09a1636445d39f4f9ec3.js:22
Rc @ dllSelf.09a1636445d39f4f9ec3.js:22
yc @ dllSelf.09a1636445d39f4f9ec3.js:22
(匿名) @ dllSelf.09a1636445d39f4f9ec3.js:22
e.unstable_runWithPriority @ dllSelf.09a1636445d39f4f9ec3.js:30
Yi @ dllSelf.09a1636445d39f4f9ec3.js:22
Ki @ dllSelf.09a1636445d39f4f9ec3.js:22
Gi @ dllSelf.09a1636445d39f4f9ec3.js:22
hc @ dllSelf.09a1636445d39f4f9ec3.js:22
ko @ dllSelf.09a1636445d39f4f9ec3.js:22
(匿名) @ BigScreen.7a256132.js:1
Promise.then(异步)
(匿名) @ BigScreen.7a256132.js:1
(匿名) @ BigScreen.7a256132.js:1
Promise.then(异步)
(匿名) @ BigScreen.7a256132.js:1
getDatas @ BigScreen.7a256132.js:1
(匿名) @ BigScreen.7a256132.js:1
ga @ dllSelf.09a1636445d39f4f9ec3.js:22
Pc @ dllSelf.09a1636445d39f4f9ec3.js:22
e.unstable_runWithPriority @ dllSelf.09a1636445d39f4f9ec3.js:30
Yi @ dllSelf.09a1636445d39f4f9ec3.js:22
Cc @ dllSelf.09a1636445d39f4f9ec3.js:22
(匿名) @ dllSelf.09a1636445d39f4f9ec3.js:22
U @ dllSelf.09a1636445d39f4f9ec3.js:30
O.port1.onmessage @ dllSelf.09a1636445d39f4f9ec3.js:30
```

**Comment by Mowen-M** [comment]
+1
