### ISSUE TITLE
启动后异常退出了

### ISSUE THREAD

**Issue by ysicing** [hacklcx/HFish#24]
报错信息如下
```
redis  231
更新数据失败
panic: database is locked

goroutine 296 [running]:
HFish/error.Check(...)
	/root/go/HFish/error/error.go:11
HFish/core/dbUtil.Update(0xccbb17, 0x32, 0xc0000a1f90, 0x2, 0x2, 0x0)
	/root/go/HFish/core/dbUtil/dbUtil.go:89 +0x338
HFish/core/report.ReportUpdateRedis(0xc0001a91eb, 0x3, 0xc00024a980, 0xb)
	/root/go/HFish/core/report/report.go:249 +0x109
created by HFish/core/protocol/redis.handleConnection.func5
	/root/go/HFish/core/protocol/redis/redis.go:112 +0x23e
```

**Comment by sanjinhub** [comment]
等新版本，会修复这些问题。

**Comment by ysicing** [comment]
已经修复了这个问题？
