### ISSUE TITLE
windows上启动报错

### ISSUE THREAD

**Issue by fatfatdog7** [hacklcx/HFish#89]
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in produ
ction.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] Loaded HTML Templates (2):
        -
        - index.html

[GIN-debug] GET    /static/*filepath         --> HFish/vendor/github.com/gin-gon
ic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] HEAD   /static/*filepath         --> HFish/vendor/github.com/gin-gon
ic/gin.(*RouterGroup).createStaticHandler.func1 (2 handlers)
[GIN-debug] GET    /                         --> HFish/utils/setting.RunDeep.fun
c1 (2 handlers)
[GIN-debug] POST   /api/v1/post/deep_report  --> HFish/view/api.ReportDeepWeb (3
 handlers)
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in produ
ction.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /api/v1/post/plug_report  --> HFish/view/api.ReportPlugWeb (3
 handlers)
panic: interface conversion: interface {} is nil, not int64

goroutine 1 [running]:
HFish/utils/setting.initCahe()
        /ext-go/1/src/HFish/utils/setting/setting.go:159 +0xcec
HFish/utils/setting.Run()
        /ext-go/1/src/HFish/utils/setting/setting.go:392 +0xf00
main.main()
        /ext-go/1/src/HFish/main.go:22 +0x1c3

**Comment by fatfatdog7** [comment]
0.6.3版本缺失文件，需在0.6.2得基础上覆盖。。没有看到作者得提示。。。
